name: Trigger Webhook on Push to Main

on:
  push:
    branches:
      - main

jobs:
  trigger-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Call Webhook URL
        run: |
          curl -X GET "http://panel.4be.my.id/hook?access_key=DEAB6bgVKNCeYPwjkqu01ipYynvp5WOM3ud4kDCMtwoDHke2"
